services:
  keycloak:
    image: quay.io/keycloak/keycloak:18.0.0
    depends_on:
      - postgres
    container_name: keycloak
    environment:
      KEYCLOAK_ADMIN: admin
      KEYCLOAK_ADMIN_PASSWORD: admin
    ports:
      - 8080:8080
    command: start-dev
