version: "3.2"
services:
  zipkin:
    image: openzipkin/zipkin:2
    container_name: zipkin
    ports:
      - 9411:9411
  rabbitmq:
    image: rabbitmq:3-management
    container_name: rabbitmq
    restart: always
    ports:
      - 5672:5672
      - 15672:15672
    environment:
      - RABBITMQ_DEFAULT_USER=guest
      - RABBITMQ_DEFAULT_PASS=guest

