create table article
(
    id_article       varchar(255) not null,
    title            varchar(255),
    url              varchar(255),
    editor_id_editor bigint,
    primary key (id_article)
);


create table editor
(
    id_editor bigint generated by default as identity,
    name      varchar(255),
    primary key (id_editor)
);


alter table article
    add constraint FKpaa4le1ty1rpkx0gmvwclhq1d
        foreign key (editor_id_editor)
            references editor