server:
  port: 8003
  servlet:
    context-path: /serie/

spring:
  application:
    name: serie-service
    zipkin:
      base-url: http://zipkin-service:9411/
  data:
    mongodb:
      host: mongodb
      port: 27017
      database: serie
  config:
    import: optional:configserver:http://config-server:8888/
  cloud:
    config:
      profile: dev
  rabbitmq:
    username: guest
    password: guest
    host: rabbitmq-service
    port: 5672
queue:
  movie:
    name: MovieQueue

eureka:
  instance:
    hostname: eureka-service
  client:
    registerWithEureka: true
    fetchRegistry: true
    serviceUrl:
      defaultZone: http://${eureka.instance.hostname}:8761/eureka/

mensagem: hello serie service

management:
  endpoints:
    web:
      exposure:
        include: '*'
