server:
  port: 8888
spring:
  application:
    name: config
  zipkin:
    baseUrl: http://zipkin:9411/
  cloud:
    config:
      server:
        git:
          uri: https://github.com/gustavobarretto/spring-config-av1
eureka:
  instance:
    hostname: loaclhost
  client:
    registerWithEureka: true
    fetchRegistry: true
    serviceUrl:
      defaultZone: http://eureka:8761/eureka/
management:
  info:
    env:
      enabled: true
  endpoints:
    web:
      exposure:
        include: health,info
info:
  name: config-center
  author: gustavobarretto
  severity: medium