spring:
  security:
    oauth2:
      client:
        provider:
          api-gateway-service:
            issuer-uri: http://localhost:8080/realms/digital-show
        registration:
          api-gateway-service:
            provider: api-gateway-service
            client-id: events-checkout
            client-secret: Tp0xYLIFazKo7dhvY4InxaXnzEUWh28D
            authorization-grant-type: authorization_code
            redirect-uri: 'http://localhost:9090/login/oauth2/code/keycloak'
  cloud:
    gateway:
      default-filters:
        - TokenRelay
      routes:
        - id: users-service
          uri: http://localhost:8084
          predicates:
            - Path=/users/**
server:
  port: 9090