spring:
  application:
    name: servicio-eureka-server
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        format_sql: true
        dialect: org.hibernate.dialect.H2Dialect
    open-in-view: false
  h2:
    console:
      enabled: true
      path: /h2-console

server:
  port: 8761

eureka:
  client:
    fetch-registry: false
    register-with-eureka: false