spring:
  security:
    oauth2:
      resourceserver:
        jwt:
          jwk-set-uri: http://localhost:8080/realms/posts-service/protocol/openid-connect/certs
  application:
    name: ms-post
  datasource:
    url: jdbc:h2:mem:testdb;DB_CLOSE_DELAY=-1
    driverClassName: org.h2.Driver
    username: sa
    password: sa
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        format_sql: true
        dialect: org.hibernate.dialect.H2Dialect
    open-in-view: false
  h2:
    console:
      enabled: true
      path: /h2-console
  main:
    web-application-type: reactive
    allow-bean-definition-overriding: true
    allow-circular-references: true

server:
  port: 8082

jwt:
  auth:
    converter:
      resource-id: posts-app
      principal-attribute: preferred_username

app:
  cors:
    allowed-origins: http://localhost:8090

eureka:
  instance:
    hostname: localhost
    instance-id: ${spring.application.name}:${spring.application.instance_id:${random.value}}
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka
