spring:
  application:
    name: movie-service
  config:
    import: optional:configserver:http://localhost:8888
  cloud:
    config:
      profile: dev

  datasource:
    driverClassName: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/movies?useTimezone=true&serverTimezone=UTC&createDatabaseIfNotExist=true
    user: root
    password: root1234

  jpa:
    hibernate.dialect: org.hibernate.dialect.MySQL5Dialect
    hibernate.ddl-auto: create-drop
    hibernate:
      jdbc: time_zone = TimeZone
