server:
  port: 8761
eureka:
  instance:
    hostname: eureka
  client:
    register-with-eureka: false
    fetch-registry: false
spring:
  application:
    name: eureka
  zipkin:
    base-url: http://zipkin:9411/