spring:
  application:
    name: catalog-service
  config:
    import: optional:configserver:http://localhost:8888
  cloud:
    config:
      profile: dev
  rabbitmq:
    username: guest
    password: guest
    host: localhost
    port: 5672

queue:
  catalog:
    name: catalog-queue
  message: catalog up
