spring:
  application:
    name: serie-service
#  config:
#    import: optional:configserver:http://config:8888
#  cloud:
#    config:
#      profile: dev

  data:
    mongodb:
      uri: mongodb://localhost:27017/seriesdb
      database: seriesdb